"""
SQLAlchemy ORM schema definitions for the AVA metadata database.

Implements a four-table relational structure (Recording, Syllable, Embedding, Annotation)
that indexes existing HDF5 spectrogram files and NPY embeddings without storing bulk array data.
Enforces strict foreign key constraints with CASCADE delete behavior to prevent orphan records
and maintains referential integrity across all tables.

The schema follows a fail-loud philosophy where any integrity violation raises RuntimeError
immediately, ensuring corrupted metadata cannot enter analysis workflows.
"""

from datetime import datetime
from typing import Any, Dict, Optional

from sqlalchemy import Integer, String, Float, DateTime, ForeignKey, JSON
from sqlalchemy.orm import DeclarativeBase, relationship, Mapped, mapped_column


class Base(DeclarativeBase):
    """SQLAlchemy declarative base for all model definitions."""
    pass


class Recording(Base):
    """
    Recording model representing audio files with metadata and integrity validation.
    
    Stores references to original audio files with SHA-256 checksums for integrity
    verification. Each recording can contain multiple syllables extracted during
    segmentation processing.
    """
    __tablename__ = 'recording'
    
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    file_path: Mapped[str] = mapped_column(String, unique=True, nullable=False)
    checksum_sha256: Mapped[str] = mapped_column(String(64), nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.now, nullable=False)
    extra_metadata: Mapped[Optional[Dict[str, Any]]] = mapped_column(JSON, nullable=True)
    
    # Relationship with CASCADE delete behavior
    syllables = relationship("Syllable", back_populates="recording", cascade="all, delete-orphan")


class Syllable(Base):
    """
    Syllable model representing segmented audio units with spectrogram references.
    
    Each syllable corresponds to a detected vocalization unit with temporal bounds
    and references to processed spectrogram data stored in HDF5 format.
    """
    __tablename__ = 'syllable'
    
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    recording_id: Mapped[int] = mapped_column(Integer, ForeignKey('recording.id', ondelete='CASCADE'), nullable=False)
    spectrogram_path: Mapped[str] = mapped_column(String, nullable=False)
    start_time: Mapped[float] = mapped_column(Float, nullable=False)
    end_time: Mapped[float] = mapped_column(Float, nullable=False)
    bounds_metadata: Mapped[Optional[Dict[str, Any]]] = mapped_column(JSON, nullable=True)
    
    # Relationships with CASCADE delete behavior
    recording = relationship("Recording", back_populates="syllables")
    embeddings = relationship("Embedding", back_populates="syllable", cascade="all, delete-orphan")
    annotations = relationship("Annotation", back_populates="syllable", cascade="all, delete-orphan")


class Embedding(Base):
    """
    Embedding model representing neural network-derived feature vectors.
    
    Stores references to NPY files containing embedding vectors generated by
    VAE models, with model version tracking for reproducibility.
    """
    __tablename__ = 'embedding'
    
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    syllable_id: Mapped[int] = mapped_column(Integer, ForeignKey('syllable.id', ondelete='CASCADE'), nullable=False)
    model_version: Mapped[str] = mapped_column(String, nullable=False)
    embedding_path: Mapped[str] = mapped_column(String, nullable=False)
    dimensions: Mapped[int] = mapped_column(Integer, nullable=False)
    extra_model_metadata: Mapped[Optional[Dict[str, Any]]] = mapped_column(JSON, nullable=True)
    
    # Relationship with parent syllable
    syllable = relationship("Syllable", back_populates="embeddings")


class Annotation(Base):
    """
    Annotation model for flexible key-value metadata storage.
    
    Provides extensible annotation system for storing labels, quality metrics,
    and analysis results associated with syllables.
    """
    __tablename__ = 'annotation'
    
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    syllable_id: Mapped[int] = mapped_column(Integer, ForeignKey('syllable.id', ondelete='CASCADE'), nullable=False)
    annotation_type: Mapped[str] = mapped_column(String, nullable=False)
    key: Mapped[str] = mapped_column(String, nullable=False)
    value: Mapped[str] = mapped_column(String, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.now, nullable=False)
    
    # Relationship with parent syllable
    syllable = relationship("Syllable", back_populates="annotations")